[package]
name = "camera_serial_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.7.1"
serde = { version = "1.0.219", features = ["derive"] }
speedy2d = "2.1.0"
image = "0.25.6"
