[package]
name = "camera_serial_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.7.0"
serde = { version = "1.0.219", features = ["derive"] }
simple_windows = { path = "../simple_windows" }
